// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAuTOkgNNwzpzaj4rMVE2nkVHus7-nGQ',
    appId: '1:391004197311:web:d09b1ac4ba1c110dd8510a',
    messagingSenderId: '391004197311',
    projectId: 'medica-app-f4cff',
    authDomain: 'medica-app-f4cff.firebaseapp.com',
    storageBucket: 'medica-app-f4cff.firebasestorage.app',
    measurementId: 'G-HXKV41KQCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLhLCtZ-DMdhFiV1jyOlaWG-kf_wvT3Xc',
    appId: '1:391004197311:android:17da8676f45c8f0dd8510a',
    messagingSenderId: '391004197311',
    projectId: 'medica-app-f4cff',
    storageBucket: 'medica-app-f4cff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8yvnXoRWBx5REY-6hfWHh-8HHXjGQkBY',
    appId: '1:391004197311:ios:b3cf6809ef096247d8510a',
    messagingSenderId: '391004197311',
    projectId: 'medica-app-f4cff',
    storageBucket: 'medica-app-f4cff.firebasestorage.app',
    iosBundleId: 'com.example.medicaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8yvnXoRWBx5REY-6hfWHh-8HHXjGQkBY',
    appId: '1:391004197311:ios:b3cf6809ef096247d8510a',
    messagingSenderId: '391004197311',
    projectId: 'medica-app-f4cff',
    storageBucket: 'medica-app-f4cff.firebasestorage.app',
    iosBundleId: 'com.example.medicaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKAuTOkgNNwzpzaj4rMVE2nkVHus7-nGQ',
    appId: '1:391004197311:web:e282ecfe5126d3d7d8510a',
    messagingSenderId: '391004197311',
    projectId: 'medica-app-f4cff',
    authDomain: 'medica-app-f4cff.firebaseapp.com',
    storageBucket: 'medica-app-f4cff.firebasestorage.app',
    measurementId: 'G-JCMZFTPJF5',
  );
}
